<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>

<body>
    <script>
        //async函数 返回值为promise对象 promise对象的结果由async函数执行的返回值决定
        async function main() {
            //如果返回值是一个非promise类型的数据 则结果为成功的promise对象 结果值为返回值
            // return 1111;
            //如果返回的是一个promise对象 则async的结果由promise对象的结果决定
            // return new Promise((resolve, reject) => {
            //     reject('err')
            // })
            //抛出异常 则返回结果为失败的promise对象 并且promise对象的值为抛出的值
            // throw 'err'
            //////////////////////////////////////////////////////////////////
            //await右侧的表达式一般为promise对象 但也可以是其他值

            //如果表达式是promise对象 await返回的是promise成功的值 如果await的promise失败了 就会抛出异常 需要通过try...catch捕获处理
            let p = new Promise((resolve, reject) => {
                // resolve('ok')
                reject('err')
            })
            try {
                let res = await p;

            } catch (e) {
                console.log(e);
            }

            //如果表达式是其他值 则直接将此值作为await的返回值
            //注意 await必须写在async函数中 但async函数中可以没有await
        }
        // let result = main();
        // console.log(result);
    </script>
</body>

</html>